using Microsoft.AspNetCore.Components.Web;
using Microsoft.AspNetCore.Components.WebAssembly.Hosting;
using Radzen;
using DotNetGalutinis.Client;
using Microsoft.AspNetCore.Components.Authorization;

var builder = WebAssemblyHostBuilder.CreateDefault(args);
builder.Services.AddScoped<DialogService>();
builder.Services.AddScoped<NotificationService>();
builder.Services.AddScoped<TooltipService>();
builder.Services.AddScoped<ContextMenuService>();
builder.Services.AddTransient(sp => new HttpClient { BaseAddress = new Uri(builder.HostEnvironment.BaseAddress) });
builder.Services.AddScoped<DotNetGalutinis.Client.InventoryService>();
builder.Services.AddAuthorizationCore();
builder.Services.AddHttpClient("DotNetGalutinis.Server", client => client.BaseAddress = new Uri(builder.HostEnvironment.BaseAddress));
builder.Services.AddTransient(sp => sp.GetRequiredService<IHttpClientFactory>().CreateClient("DotNetGalutinis.Server"));
builder.Services.AddScoped<DotNetGalutinis.Client.SecurityService>();
builder.Services.AddScoped<AuthenticationStateProvider, DotNetGalutinis.Client.ApplicationAuthenticationStateProvider>();
var host = builder.Build();
await host.RunAsync();